{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prefect-server.serviceAccountName" . }}
  labels:
{{- include "prefect-server.commonLabels" . | nindent 4 }}
{{- end -}}
