ldap:
  host: "ldap.aiscope.io:31675"
  managerDN: "cn=admin,dc=aiscope,dc=io"
  managerPassword: "adminpassword"
  userSearchBase: "ou=Users,dc=aiscope,dc=io"
  groupSearchBase: "ou=Groups,dc=aiscope,dc=io"
  initialCap: 10
  maxCap: 100
  poolName: "ldap"
redis:
  host: "redis.aiscope.io"
  port: 6379
  password: "password123"
  db: 1
authentication:
  jwtSecret: "aiscopeSys"
  oauthOptions:
    identityProviders:
      - name: dex
        type: OIDCIdentityProvider
        mappingMethod: auto
