apiVersion: v1
data:
  ## Tenant credentials, base64 encoded (cat config.env | base64)
  ##  export MINIO_ROOT_USER="minio"
  ##  export MINIO_ROOT_PASSWORD="minio123"
  ##  export MINIO_STORAGE_CLASS_STANDARD="EC:2"
  ##  export MINIO_BROWSER="on"
  config.env: ZXhwb3J0IE1JTklPX1JPT1RfVVNFUj0ibWxmbG93IgpleHBvcnQgTUlOSU9fUk9PVF9QQVNTV09SRD0ibWxmbG93MTIzNCIKZXhwb3J0IE1JTklPX1NUT1JBR0VfQ0xBU1NfU1RBTkRBUkQ9ImxvY2FsLXBhdGgiCmV4cG9ydCBNSU5JT19CUk9XU0VSPSJvbiIK
kind: Secret
metadata:
  name: dilu-tenant-external
  namespace: ai
type: Opaque
