# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/tenant.aiscope_workspaces.yaml
- bases/iam.aiscope_users.yaml
- bases/iam.aiscope_workspaceroles.yaml
- bases/iam.aiscope_workspacerolebindings.yaml
- bases/iam.aiscope_globalroles.yaml
- bases/iam.aiscope_globalrolebindings.yaml
- bases/iam.aiscope_loginrecords.yaml
- bases/iam.aiscope_groups.yaml
- bases/iam.aiscope_groupbindings.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_workspaces.yaml
#- patches/webhook_in_users.yaml
#- patches/webhook_in_workspaceroles.yaml
#- patches/webhook_in_workspacerolebindings.yaml
#- patches/webhook_in_globalroles.yaml
#- patches/webhook_in_globalrolebindings.yaml
#- patches/webhook_in_loginrecords.yaml
#- patches/webhook_in_groups.yaml
#- patches/webhook_in_groupbindings.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_workspaces.yaml
#- patches/cainjection_in_users.yaml
#- patches/cainjection_in_workspaceroles.yaml
#- patches/cainjection_in_workspacerolebindings.yaml
#- patches/cainjection_in_globalroles.yaml
#- patches/cainjection_in_globalrolebindings.yaml
#- patches/cainjection_in_loginrecords.yaml
#- patches/cainjection_in_groups.yaml
#- patches/cainjection_in_groupbindings.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
